-- Active: 1785894373743@@ep-lingering-dawn-avtgw7cj-pooler.c-11.us-east-1.aws.neon.tech@5432@curso_fullstack@prueba
/*
TAREAS ->
    TABLAS
        TAREA
            - NOMBRE
            - DESCRIPCION
            - ESTADO

*/
DROP TABLE IF EXISTS REL_USER_TASK;
DROP TABLE IF EXISTS TASK_STATUS;
DROP TABLE IF EXISTS TASK;
DROP TABLE IF EXISTS USER_TASK;
CREATE TABLE TASK(
	ID SERIAL,
	TASK VARCHAR(128),
    DESCRIPTION VARCHAR(256),
    STATE BIT,
    CREATION_DATE TIMESTAMP,
	CONSTRAINT PK_TAREA PRIMARY KEY(ID)
);

CREATE TABLE USER_TASK(
    ID SERIAL,
    FIRST_NAME VARCHAR(64) NOT NULL,
    LAST_NAME VARCHAR(64) NOT NULL,
    EMAIL VARCHAR(64) NOT NULL UNIQUE,
    PASSWORD VARCHAR(32) NOT NULL,
    CONSTRAINT PK_USER PRIMARY KEY (ID)
);

CREATE TABLE TASK_STATUS(
    ID SERIAL,
    STATUS VARCHAR(20) NOT NULL CHECK(STATUS IN ('PENDIENTE', 'EN PROGRESO', 'FINALIZADA', 'CANCELADA')),
    CONSTRAINT PK_TASK_STATUS PRIMARY KEY(ID)
);

CREATE TABLE REL_USER_TASK(
    ID_USER INTEGER REFERENCES USER_TASK(ID),
    ID_TASK INTEGER REFERENCES TASK(ID)
);

